time python client.py config.txt download bigf1 ./download
time python client.py config.txt download bigf2 ./download
time python client.py config.txt download bigf3 ./download
time python client.py config.txt download bigf4 ./download
time python client.py config.txt download bigf5 ./download
time python client.py config.txt download bigf6 ./download
time python client.py config.txt download bigf7 ./download
time python client.py config.txt download bigf8 ./download
time python client.py config.txt download bigf9 ./download
time python client.py config.txt download bigf10 ./download
time python client.py config.txt download bigf11 ./download
time python client.py config.txt download bigf12 ./download
time python client.py config.txt download bigf13 ./download
time python client.py config.txt download bigf14 ./download
time python client.py config.txt download bigf15 ./download
time python client.py config.txt download bigf16 ./download
time python client.py config.txt download bigf17 ./download
time python client.py config.txt download bigf18 ./download
time python client.py config.txt download bigf19 ./download
time python client.py config.txt download bigf20 ./download
time python client.py config.txt download bigf21 ./download
time python client.py config.txt download bigf22 ./download
time python client.py config.txt download bigf23 ./download
time python client.py config.txt download bigf24 ./download
time python client.py config.txt download bigf25 ./download
