time python client.py config.txt download f1 ./download
time python client.py config.txt download f2 ./download
time python client.py config.txt download f3 ./download
time python client.py config.txt download f4 ./download
time python client.py config.txt download f5 ./download
time python client.py config.txt download f6 ./download
time python client.py config.txt download f7 ./download
time python client.py config.txt download f8 ./download
time python client.py config.txt download f9 ./download
time python client.py config.txt download f10 ./download
time python client.py config.txt download f11 ./download
time python client.py config.txt download f12 ./download
time python client.py config.txt download f13 ./download
time python client.py config.txt download f14 ./download
time python client.py config.txt download f15 ./download
time python client.py config.txt download f16 ./download
time python client.py config.txt download f17 ./download
time python client.py config.txt download f18 ./download
time python client.py config.txt download f19 ./download
time python client.py config.txt download f20 ./download
time python client.py config.txt download f21 ./download
time python client.py config.txt download f22 ./download
time python client.py config.txt download f23 ./download
time python client.py config.txt download f24 ./download
time python client.py config.txt download f25 ./download
