time python client.py config.txt upload ./data/bigf1
time python client.py config.txt upload ./data/bigf2
time python client.py config.txt upload ./data/bigf3
time python client.py config.txt upload ./data/bigf4
time python client.py config.txt upload ./data/bigf5
time python client.py config.txt upload ./data/bigf6
time python client.py config.txt upload ./data/bigf7
time python client.py config.txt upload ./data/bigf8
time python client.py config.txt upload ./data/bigf9
time python client.py config.txt upload ./data/bigf10
time python client.py config.txt upload ./data/bigf11
time python client.py config.txt upload ./data/bigf12
time python client.py config.txt upload ./data/bigf13
time python client.py config.txt upload ./data/bigf14
time python client.py config.txt upload ./data/bigf15
time python client.py config.txt upload ./data/bigf16
time python client.py config.txt upload ./data/bigf17
time python client.py config.txt upload ./data/bigf18
time python client.py config.txt upload ./data/bigf19
time python client.py config.txt upload ./data/bigf20
time python client.py config.txt upload ./data/bigf21
time python client.py config.txt upload ./data/bigf22
time python client.py config.txt upload ./data/bigf23
time python client.py config.txt upload ./data/bigf24
time python client.py config.txt upload ./data/bigf25
