time python client.py config.txt upload ./data/f1
time python client.py config.txt upload ./data/f2
time python client.py config.txt upload ./data/f3
time python client.py config.txt upload ./data/f4
time python client.py config.txt upload ./data/f5
time python client.py config.txt upload ./data/f6
time python client.py config.txt upload ./data/f7
time python client.py config.txt upload ./data/f8
time python client.py config.txt upload ./data/f9
time python client.py config.txt upload ./data/f10
time python client.py config.txt upload ./data/f11
time python client.py config.txt upload ./data/f12
time python client.py config.txt upload ./data/f13
time python client.py config.txt upload ./data/f14
time python client.py config.txt upload ./data/f15
time python client.py config.txt upload ./data/f16
time python client.py config.txt upload ./data/f17
time python client.py config.txt upload ./data/f18
time python client.py config.txt upload ./data/f19
time python client.py config.txt upload ./data/f20
time python client.py config.txt upload ./data/f21
time python client.py config.txt upload ./data/f22
time python client.py config.txt upload ./data/f23
time python client.py config.txt upload ./data/f24
time python client.py config.txt upload ./data/f25
